\documentclass[article, shortnames, nojss]{jss}
\usepackage[utf8]{inputenc}
\usepackage{amsmath}
\usepackage{enumerate}
\usepackage{multirow}
\DeclareMathOperator*{\argmax}{arg\,max}
% \VignetteIndexEntry{Massive and Integrative Gene Set Analysis}
% \VignetteKeyword{singular enrichment analysis}
% \VignetteKeyword{over representation analysis}
% \VignetteKeyword{gene set enrichment analysis}
% \VignetteKeyword{functional class scoring}
% \VignetteKeyword{big omics data}

% \VignetteDepends{MIGSA}

\author{Juan C Rodriguez\\CONICET\\Universidad Cat\'{o}lica de C\'{o}rdoba\\
Universidad Nacional de C\'{o}rdoba
\And Crist\'{o}bal Fresno\\CONICET\\Universidad Cat\'{o}lica de C\'{o}rdoba
\AND Andrea S Llera\\CONICET\\Fundaci\'{o}n Instituto 
Leloir \And Elmer A Fern\'{a}ndez\\CONICET\\Universidad Cat\'{o}lica de
C\'{o}rdoba\\Universidad Nacional de C\'{o}rdoba}

\title{\pkg{MIGSA}: Getting TCGA datasets}

%% for pretty printing and a nice hypersummary also set:
%% comma-separated
\Plainauthor{Juan C Rodriguez, Crist\'{o}bal Fresno, Andrea S Llera, Elmer A 
    Fern\'{a}ndez}
%% without formatting
\Plaintitle{MIGSA: Getting TCGA datasets}
%% a short title (if necessary)
\Shorttitle{\pkg{MIGSA}: Getting TCGA datasets}

%% an abstract and keywords
\Abstract{
In this vignette we are going to show how we got the data used as 
\textit{tcgaMAdata.RData} which can be loaded using 
loadMIGSAdata("tcgaMAdata") and \textit{tcgaRNAseqData.RData} which can be 
loaded using loadMIGSAdata("tcgaRNAseqData").
}
\Keywords{singular enrichment analysis, over representation analysis, gene set 
enrichment analysis, functional class scoring, big omics data}

%% without formatting
\Plainkeywords{singular enrichment analysis, over representation analysis, 
gene set enrichment analysis, functional class scoring, big omics data}
%% at least one keyword must be supplied 

%% The address of (at least) one author should be given  
%% in the following format:
\Address{
Juan C Rodriguez, Crist\'{o}bal Fresno \& Elmer A Fern\'{a}ndez\\
Bioscience Data Mining Group\\ 
Facultad de Ingenier\'{i}a\\ 
Universidad Cat\'{o}lica de C\'{o}rdoba - CONICET\\ 
X5016DHK C\'{o}rdoba, Argentina\\ 
E-mail: \email{jcrodriguez@bdmg.com.ar, cfresno@bdmg.com.ar, \\ 
efernandez@bdmg.com.ar}\\
URL: \url{http://www.bdmg.com.ar/}\\
}

\begin{document}
\SweaveOpts{concordance=TRUE}
% \SweaveOpts{concordance=FALSE}

% \begin{titlepage}
% \title{
%     \textbf{IFA:} \\
%     Integrative Functional Analysis User's Guide
% }
% 
% \author{
%Juan C. Rodriguez\\
%\texttt{jcrodriguez@bdmg.com.ar}
%\and
%Elmer A Fern\'{a}ndez\\
%\texttt{efernandez@bdmg.com.ar}
% }
% % \textit{}
% \date{September 19, 2016}
% \end{titlepage}
% 
% \begin{center}
% \huge{
%   \textbf{IFA:} \\
%   Integrative Functional Analysis User's Guide
% }
% 
% \vspace{8pt}
% 
% \large{
%   Juan C. Rodriguez$^{1,2}$ \quad Elmer A Fern\'{a}ndez$^{1,3}$ \\
%     \texttt{jcrodriguez@bdmg.com.ar efernandez@bdmg.com.ar} \\
% %    \texttt{\{jcrodriguez, efernandez\}@bdmg.com.ar} \\
%     \vspace{2pt}
%     \small{
%     $^{1}$ UA AREA CS. AGR. ING. BIO. Y S, Universidad Cat\'{o}lica de 
% C\'{o}rdoba, CONICET, C\'{o}rdoba, Argentina \\
%     $^{2}$ Facultad de Matem\'{a}tica, Astronom\'{i}a y F\'{i}sica, 
% Universidad Nacional de C\'{o}rdoba, C\'{o}rdoba, Argentina \\
%     $^{3}$ Facultad de Ciencias Exactas, F\'{i}sicas y Naturales, 
% Universidad Nacional de C\'{o}rdoba, C\'{o}rdoba, Argentina \\
%     }
%     \vspace{8pt}
%     First edition September 19, 2016 \\
%     Last revised \today \\
%     \vspace{8cm}
%     \noindent\fbox{
%             \parbox{\textwidth}{
%                 This free open-source software implements academic 
% research by the
%                 authors and co-workers. If you use it, please support 
% the project by
%                 citing the journal article listed in Section
%                 \ref{citeSection}.
%             }
%     }
% }
% \end{center}
% \clearpage

\section{Getting the data}
From the TCGA data portal the Breast invasive carcinoma (BRCA) microarray and 
RNAseq datasets present at the date were downloaded. PAM50 subtypes Basal vs. 
Luminal A were evaluated. With these subjects, \textit{tcgaMAdata.RData} and 
\textit{tcgaRNAseqData.RData} were built.

<<echo=FALSE>>=
library(MIGSA);
tcgaMAdata <- loadMIGSAdata("tcgaMAdata");
@

\subsection{Basal-like subjects}
Basal-like TCGA subjects identifiers used:

<<basalSubjects>>=
names(tcgaMAdata$subtypes)[ tcgaMAdata$subtypes == "Basal" ];
@

\subsection{Luminal A subjects}
Luminal A TCGA subjects identifiers used:

<<basalSubjects>>=
names(tcgaMAdata$subtypes)[ tcgaMAdata$subtypes == "LumA" ];
@

\section*{Session Info}
<<Session Info, echo=true>>=
sessionInfo()
@

% \bibliography{MIGSA-vignette}

\end{document}